# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_bankfulldetection.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BankFullDetection(object):
    def setupUi(self, BankFullDetection):
        BankFullDetection.setObjectName("BankFullDetection")
        BankFullDetection.resize(460, 525)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(BankFullDetection)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(BankFullDetection)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setAcceptDrops(False)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("QGroupBox {border:1px solid rgb(0, 0, 0); }")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(9, 25, -1, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboVector = QtWidgets.QComboBox(self.groupBox)
        self.comboVector.setObjectName("comboVector")
        self.horizontalLayout.addWidget(self.comboVector)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.stepXSspin = QtWidgets.QSpinBox(self.groupBox)
        self.stepXSspin.setMaximum(10000)
        self.stepXSspin.setSingleStep(10)
        self.stepXSspin.setProperty("value", 50)
        self.stepXSspin.setObjectName("stepXSspin")
        self.horizontalLayout_2.addWidget(self.stepXSspin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.widthXSspin = QtWidgets.QSpinBox(self.groupBox)
        self.widthXSspin.setMaximum(1000)
        self.widthXSspin.setProperty("value", 500)
        self.widthXSspin.setObjectName("widthXSspin")
        self.horizontalLayout_4.addWidget(self.widthXSspin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.genXSbtn = QtWidgets.QPushButton(self.groupBox)
        self.genXSbtn.setObjectName("genXSbtn")
        self.verticalLayout_3.addWidget(self.genXSbtn)
        self.genLbtn = QtWidgets.QPushButton(self.groupBox)
        self.genLbtn.setObjectName("genLbtn")
        self.verticalLayout_3.addWidget(self.genLbtn)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setStyleSheet("QGroupBox {border:1px solid rgb(0, 0, 0); }")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboDEM = QtWidgets.QComboBox(self.groupBox_2)
        self.comboDEM.setObjectName("comboDEM")
        self.horizontalLayout_3.addWidget(self.comboDEM)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.nVsteps = QtWidgets.QSpinBox(self.groupBox_2)
        self.nVsteps.setSuffix("")
        self.nVsteps.setMinimum(50)
        self.nVsteps.setMaximum(2000)
        self.nVsteps.setProperty("value", 100)
        self.nVsteps.setObjectName("nVsteps")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nVsteps)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.minVdep = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.minVdep.setSingleStep(0.05)
        self.minVdep.setProperty("value", 0.5)
        self.minVdep.setObjectName("minVdep")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minVdep)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.chbSlopeLim = QtWidgets.QCheckBox(self.groupBox_2)
        self.chbSlopeLim.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chbSlopeLim.setText("")
        self.chbSlopeLim.setObjectName("chbSlopeLim")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chbSlopeLim)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.ShpSaveLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.ShpSaveLine.setObjectName("ShpSaveLine")
        self.horizontalLayout_5.addWidget(self.ShpSaveLine)
        self.ShpSaveBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.ShpSaveBtn.setObjectName("ShpSaveBtn")
        self.horizontalLayout_5.addWidget(self.ShpSaveBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.buttonProf = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonProf.setObjectName("buttonProf")
        self.verticalLayout.addWidget(self.buttonProf)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.selXS = QtWidgets.QPushButton(self.tab_3)
        self.selXS.setObjectName("selXS")
        self.horizontalLayout_6.addWidget(self.selXS)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.layout_plot = QtWidgets.QVBoxLayout()
        self.layout_plot.setObjectName("layout_plot")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setObjectName("widget")
        self.layout_plot.addWidget(self.widget)
        self.verticalLayout_4.addLayout(self.layout_plot)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.nbExSbox = QtWidgets.QSpinBox(self.tab_5)
        self.nbExSbox.setMinimum(1)
        self.nbExSbox.setMaximum(100)
        self.nbExSbox.setObjectName("nbExSbox")
        self.horizontalLayout_7.addWidget(self.nbExSbox)
        self.plotBtn = QtWidgets.QPushButton(self.tab_5)
        self.plotBtn.setObjectName("plotBtn")
        self.horizontalLayout_7.addWidget(self.plotBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.line_3 = QtWidgets.QFrame(self.tab_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.layout_val = QtWidgets.QVBoxLayout()
        self.layout_val.setObjectName("layout_val")
        self.widget_val = QtWidgets.QWidget(self.tab_5)
        self.widget_val.setObjectName("widget_val")
        self.layout_val.addWidget(self.widget_val)
        self.verticalLayout_6.addLayout(self.layout_val)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(BankFullDetection)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)

        self.retranslateUi(BankFullDetection)
        self.tabWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(BankFullDetection.accept)
        self.buttonBox.rejected.connect(BankFullDetection.reject)
        QtCore.QMetaObject.connectSlotsByName(BankFullDetection)

    def retranslateUi(self, BankFullDetection):
        _translate = QtCore.QCoreApplication.translate
        BankFullDetection.setWindowTitle(_translate("BankFullDetection", "Automatic Bankfull detection"))
        self.groupBox.setTitle(_translate("BankFullDetection", "XS Generator"))
        self.label.setText(_translate("BankFullDetection", "riverbed axis"))
        self.label_3.setText(_translate("BankFullDetection", "step of XS"))
        self.stepXSspin.setSuffix(_translate("BankFullDetection", " m"))
        self.label_4.setText(_translate("BankFullDetection", "Width of XS"))
        self.widthXSspin.setSuffix(_translate("BankFullDetection", " m"))
        self.genXSbtn.setText(_translate("BankFullDetection", "Generate XS"))
        self.genLbtn.setText(_translate("BankFullDetection", "Generate line from XS"))
        self.groupBox_2.setTitle(_translate("BankFullDetection", "Bankfull detection"))
        self.label_2.setText(_translate("BankFullDetection", "DEM"))
        self.label_5.setText(_translate("BankFullDetection", "Number o vertical steps\n"
"(default 100)"))
        self.label_6.setText(_translate("BankFullDetection", "Minimum hydraulic depth"))
        self.minVdep.setSuffix(_translate("BankFullDetection", " m"))
        self.label_7.setText(_translate("BankFullDetection", "Detect only first slope"))
        self.label_8.setText(_translate("BankFullDetection", "Output file"))
        self.ShpSaveBtn.setText(_translate("BankFullDetection", "Browse"))
        self.buttonProf.setText(_translate("BankFullDetection", "Run tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("BankFullDetection", "Main tool"))
        self.label_9.setText(_translate("BankFullDetection", "Select one feature from XS"))
        self.selXS.setText(_translate("BankFullDetection", "Single XS plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("BankFullDetection", "Graph"))
        self.label_10.setText(_translate("BankFullDetection", "Set executions number :"))
        self.plotBtn.setText(_translate("BankFullDetection", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("BankFullDetection", "Validation"))

